from ckanext.defrareports.lib.reports.publishing_reports import publishing_history_report
from ckanext.defrareports.lib.reports.access_reports import access_history_report
from ckanext.defrareports.lib.reports.broken_resource_reports import broken_resource_report
from ckanext.defrareports.lib.reports.quality_report import quality_report
from ckanext.defrareports.lib.reports.system_stats_report import system_stats_report
